### ISSUE TITLE
Usage of $noty inside vuex

### ISSUE THREAD

**Issue by ChunAllen** [renoguyon/vuejs-noty#10]
How can I use the $noty inside Vuex modules? 

Currently what I'm doing is this: 
**pages/index.vue**
```
export default { 
  created() {
    this.$store.dispatch('getUsers, this) // currently I need to pass this in order to use the $noty inside vuex module
  }, 
  computed: {
    users() {
      return this.$store.getters.users;
    }
  }
}
</script>
```
**store/modules/users.js**
```
export const state = () => ({
   users: []
});

export const actions = () => ({
  getUsers({commit}, context) {
      context.$noty.success('HELLO WORLD') `How can I use $noty without passing the this from the component?`
  } 
});
```

**Comment by renoguyon** [comment]
Hey, have you tried this syntax?

store/modules/users.js
`
import Vue from 'vue';

export const state = () => ({
   users: []
});

export const actions = () => ({
  getUsers({commit}) {
      Vue.noty.success('HELLO WORLD');
  } 
});
`
Let me know!

**Comment by ChunAllen** [comment]
It's working now. Thanks @renoguyon
