### ISSUE TITLE
No access to API Methods.

### ISSUE THREAD

**Issue by idelsink** [renoguyon/vuejs-noty#4]
I have no acces to the API methods as described in https://ned.im/noty/#/api.

When adding a message, I want to be able to close the message programmatically via the instance created as on line https://github.com/renoguyon/vuejs-noty/blob/master/src/index.js#L26. 
Using the `close()` method.

Perhaps the methods, like `success`, `error`, ...etc, should return the instance of the created object.

**Comment by renoguyon** [comment]
Pull request merged, thank you :)
